//! Emitting the [`crate::ir`] as formatted Rust source.
//!
//! Items are built as a [`proc_macro2::TokenStream`] with `quote!`, parsed into
//! a [`syn::File`] (which guarantees the output is syntactically valid Rust),
//! and pretty-printed with `prettyplease`.

mod axum;
mod models;
mod operation;
mod reqwest;
mod servers;
mod usage;

use std::collections::HashMap;

use proc_macro2::TokenStream;
use quote::quote;

use crate::emit::models::SerdeDerives;
use crate::error::Error;
use crate::error::Result;
use crate::ir::Module;
use crate::ir::Multipart;
use crate::ir::NegotiatedBody;
use crate::ir::RustType;
use crate::ir::ServerUrls;
use crate::ir::Service;
use crate::naming::Case;
use crate::naming::to_ident;

/// Emits a server interface for a lowered [`Service`] as top-level token items.
///
/// One implementation per target framework; `AxumServer` is the only one today.
pub trait ServerEmitter {
    /// Emit the server-interface items (trait, response enums, router, handlers).
    fn emit(&self, service: &Service) -> Result<Vec<TokenStream>>;
}

/// Emits a client for a lowered [`Service`] as top-level token items.
///
/// One implementation per target HTTP library; `ReqwestClient` is the only one
/// today.
pub trait ClientEmitter {
    /// Emit the client items (error type, `Client` struct, per-operation methods,
    /// and the response types they return).
    fn emit(&self, service: &Service) -> Result<Vec<TokenStream>>;
}

/// Header prepended to every generated file.
const HEADER: &str = "// Code generated by oapi-codegen-rust. DO NOT EDIT.\n\n";

/// Render a module of IR items into formatted Rust source.
///
/// Each top-level item is parsed and pretty-printed on its own so that a blank
/// line separates adjacent items — prettyplease otherwise emits them with no
/// separation, which is hard to read when many `pub` items follow each other.
pub fn emit_module(module: &Module, server_urls: Option<&ServerUrls>) -> Result<String> {
    let mut items = module_items(module, &HashMap::new())?;
    items.extend(server_url_items(server_urls)?);
    return render(&items);
}

/// Which generator interfaces to emit alongside the shared per-operation types.
///
/// At least one field is set whenever [`emit_flat`] is called.
#[derive(Debug, Clone, Copy)]
pub struct Targets {
    /// Emit the axum server interface.
    pub server: bool,
    /// Emit the blocking `reqwest` client.
    pub client: bool,
}

/// A fixed type name the generator emits at the crate root for a given target,
/// which a component-schema model must not collide with.
#[derive(Debug, Clone, Copy)]
pub struct ReservedTypeName {
    /// The reserved Rust identifier (e.g. `Api`).
    pub name: &'static str,
    /// Human-readable description of what emits it (e.g. `server interface
    /// trait`), used in the collision error.
    pub description: &'static str,
}

/// The crate-root type names the requested `targets` emit. A component schema
/// whose generated name matches one of these would produce a duplicate item, so
/// [`crate::lower::check_type_name_collisions`] rejects it up front.
pub fn reserved_type_names(targets: Targets) -> Vec<ReservedTypeName> {
    let mut names = Vec::new();
    if targets.server {
        names.push(ReservedTypeName {
            name: axum::API_TRAIT_NAME,
            description: "server interface trait",
        });
    }
    if targets.client {
        names.push(ReservedTypeName {
            name: reqwest::CLIENT_STRUCT_NAME,
            description: "client struct",
        });
        names.push(ReservedTypeName {
            name: reqwest::CLIENT_ERROR_NAME,
            description: "client error enum",
        });
    }
    return names;
}

/// Render a module as a flat file: the shared component models and per-operation
/// types at the crate root, followed by the requested generator interfaces.
///
/// The query/header/cookie inputs, request and response bodies, and response
/// enum an operation contributes are the same types whichever generator uses
/// them, so [`operation::emit_operation_types`] emits them once. The axum server
/// then adds its extractor and `IntoResponse` impls, and the `reqwest` client
/// its request-building methods, both naming those root types directly. Server
/// and client can therefore share a single file without a name clash.
pub fn emit_flat(
    module: &Module,
    service: &Service,
    server_urls: Option<&ServerUrls>,
    targets: Targets,
) -> Result<String> {
    let derives = usage::model_derives(module, service, targets);
    let mut items = module_items(module, &derives)?;
    items.extend(server_url_items(server_urls)?);
    for operation in &service.operations {
        items.extend(operation::emit_operation_types(operation, targets)?);
    }
    if targets.server {
        items.extend(axum::AxumServer.emit(service)?);
    }
    if targets.client {
        items.extend(reqwest::ReqwestClient.emit(service)?);
    }
    return render(&items);
}

/// Emit the server-URL items, or nothing when the feature is disabled or the
/// spec declares no servers.
fn server_url_items(server_urls: Option<&ServerUrls>) -> Result<Vec<TokenStream>> {
    return match server_urls {
        Some(server_urls) => servers::emit_server_urls(server_urls),
        None => Ok(Vec::new()),
    };
}

/// Lower every IR item in a module into its token stream, applying each item's
/// serde derive set from `derives` (defaulting to both traits when absent).
fn module_items(module: &Module, derives: &HashMap<String, SerdeDerives>) -> Result<Vec<TokenStream>> {
    let mut items = Vec::with_capacity(module.items.len());
    for item in &module.items {
        let serde = derives.get(item.name()).copied().unwrap_or_else(SerdeDerives::both);
        items.push(models::emit_item(item, serde)?);
    }
    return Ok(items);
}

/// Pretty-print a sequence of top-level items, one blank line apart, prefixed
/// with the generated-file header.
fn render(items: &[TokenStream]) -> Result<String> {
    let mut out = String::from(HEADER);
    out.push_str(&render_body(items)?);
    return Ok(out);
}

/// Pretty-print a sequence of items, one blank line apart, without the header.
///
/// Each item is parsed and pretty-printed on its own so that a blank line
/// separates adjacent items — prettyplease otherwise emits them with no
/// separation, which is hard to read when many `pub` items follow each other.
fn render_body(items: &[TokenStream]) -> Result<String> {
    let mut out = String::new();
    for (index, tokens) in items.iter().enumerate() {
        let file = syn::parse2::<syn::File>(tokens.clone()).map_err(|source| {
            return Error::InvalidGeneratedCode { source };
        })?;
        if index > 0 {
            out.push('\n');
        }
        out.push_str(&prettyplease::unparse(&file));
    }
    return Ok(out);
}

/// Render a doc attribute, or nothing when there is no documentation.
pub(crate) fn doc_attr(doc: &Option<String>) -> TokenStream {
    let tokens = match doc {
        Some(text) => {
            // Leading space matches the `/// text` desugaring rustfmt produces.
            let spaced = format!(" {text}");
            quote! { #[doc = #spaced] }
        }
        None => quote! {},
    };
    return tokens;
}

/// Render a Rust type expression.
pub(crate) fn emit_type(ty: &RustType) -> Result<TokenStream> {
    let tokens = match ty {
        RustType::Bool => quote! { bool },
        RustType::I32 => quote! { i32 },
        RustType::I64 => quote! { i64 },
        RustType::F64 => quote! { f64 },
        RustType::String => quote! { String },
        RustType::Value => quote! { serde_json::Value },
        RustType::Date => quote! { chrono::NaiveDate },
        RustType::DateTime => quote! { chrono::DateTime<chrono::Utc> },
        RustType::Uuid => quote! { uuid::Uuid },
        RustType::Bytes => quote! { Vec<u8> },
        RustType::Vec(inner) => {
            let inner = emit_type(inner)?;
            quote! { Vec<#inner> }
        }
        RustType::Map(inner) => {
            let inner = emit_type(inner)?;
            quote! { std::collections::HashMap<String, #inner> }
        }
        RustType::Option(inner) => {
            let inner = emit_type(inner)?;
            quote! { Option<#inner> }
        }
        RustType::Named(name) => {
            let ident = to_ident(name, Case::Pascal).to_token();
            quote! { #ident }
        }
        RustType::External { module, name } => {
            let path: syn::Path = syn::parse_str(module).map_err(|err| {
                return Error::UnsupportedSchema {
                    path: "import-mapping".to_owned(),
                    reason: format!("module path `{module}` is not a valid Rust path expression: {err}"),
                };
            })?;
            let ident = to_ident(name, Case::Pascal).to_token();
            quote! { #path::#ident }
        }
        RustType::Verbatim(text) => {
            let parsed: TokenStream = text.parse().map_err(|err: proc_macro2::LexError| {
                return Error::UnsupportedSchema {
                    path: "x-rust-type".to_owned(),
                    reason: format!("value `{text}` is not a valid Rust type expression: {err}"),
                };
            })?;
            parsed
        }
    };
    return Ok(tokens);
}

/// Emit the plain per-operation multipart struct (`<Op>Multipart`) shared by the
/// server extractor and the client request builder: one public field per part,
/// wrapped in `Option` when the part is optional. The server augments this with a
/// `FromRequest` impl; the client reads the fields to build a `reqwest` form.
pub(crate) fn emit_multipart_struct(multipart: &Multipart) -> Result<TokenStream> {
    let name = multipart.name.to_token();
    let mut field_defs = Vec::with_capacity(multipart.fields.len());
    for field in &multipart.fields {
        let ident = field.rust_name.to_token();
        let ty = emit_type(&field.ty)?;
        let field_ty = if field.optional {
            quote! { Option<#ty> }
        } else {
            quote! { #ty }
        };
        field_defs.push(quote! { pub #ident: #field_ty, });
    }
    return Ok(quote! {
        #[derive(Debug, Clone)]
        pub struct #name {
            #(#field_defs)*
        }
    });
}

/// Emit the plain enum backing a negotiated (multi-content-type) body: one
/// variant per content representation, carrying that representation's decoded
/// type. Shared by the server (which augments the request enum with a
/// `FromRequest` impl and renders the response enum with `IntoResponse`) and the
/// client (which matches on it to build a request or decode a response).
pub(crate) fn emit_negotiated_body_enum(body: &NegotiatedBody) -> Result<TokenStream> {
    let name = body.name.to_token();
    let mut variants = Vec::with_capacity(body.variants.len());
    for variant in &body.variants {
        let ident = variant.variant.to_token();
        let ty = emit_type(&variant.body.ty)?;
        variants.push(quote! { #ident(#ty) });
    }
    return Ok(quote! {
        #[derive(Debug, Clone, PartialEq)]
        pub enum #name {
            #(#variants),*
        }
    });
}
