// Code generated by oapi-codegen-rust. DO NOT EDIT.

pub type UserId = uuid::Uuid;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq)]
pub struct Account {
    pub owner: uuid::Uuid,
}
