// Code generated by oapi-codegen-rust. DO NOT EDIT.

pub type Anything = serde_json::Value;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq)]
pub struct Envelope {
    pub payload: serde_json::Value,
}
