// Code generated by oapi-codegen-rust. DO NOT EDIT.

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq)]
pub struct IntegerFormats {
    pub plain: i64,
    pub small: i32,
    pub big: i64,
}
