// Code generated by oapi-codegen-rust. DO NOT EDIT.

/// A documented type.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq)]
pub struct Documented {
    /// The display name.
    pub name: String,
}
