// Code generated by oapi-codegen-rust. DO NOT EDIT.

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq)]
pub struct NumberFormats {
    pub plain: f64,
    pub single: f64,
    pub wide: f64,
}
