// Code generated by oapi-codegen-rust. DO NOT EDIT.

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq)]
pub struct Counters {
    pub name: String,
    #[serde(flatten)]
    pub additional_properties: std::collections::HashMap<String, i64>,
}
