// Code generated by oapi-codegen-rust. DO NOT EDIT.

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq)]
pub struct Order {
    pub shipping: OrderShipping,
}

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq)]
pub struct OrderShipping {
    pub street: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
}
