// Code generated by oapi-codegen-rust. DO NOT EDIT.

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq)]
pub struct Primitives {
    pub label: String,
    pub count: i64,
    pub ratio: f64,
    pub flag: bool,
}
