//! Keeps `docs/cli.md` in lockstep with the clap CLI definition.
//!
//! `docs/cli.md` is generated from [`oapi_codegen::cli::Cli`], so the clap
//! struct is the single source of truth. This test regenerates the reference
//! and asserts it matches the committed file, failing with the exact command to
//! refresh it. Set `UPDATE_DOCS=1` (via `make update-docs`) to write the file
//! instead of comparing.

use std::path::PathBuf;

use oapi_codegen::cli::Cli;

/// Marker prepended to the generated CLI reference so readers (and reviewers)
/// know not to edit it by hand.
const GENERATED_NOTICE: &str =
    "<!-- Generated by `make update-docs` from the clap CLI definition. DO NOT EDIT. -->\n\n";

/// Absolute path to the committed `docs/cli.md`, resolved from the crate root.
fn cli_doc_path() -> PathBuf {
    return PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../docs/cli.md");
}

/// Render the CLI reference (`docs/cli.md`) from the clap definition.
fn reference_markdown() -> String {
    let options = clap_markdown::MarkdownOptions::new()
        .title("oapi-codegen CLI reference".to_owned())
        .show_footer(false)
        .show_table_of_contents(false);
    let body = clap_markdown::help_markdown_custom::<Cli>(&options);
    return format!("{GENERATED_NOTICE}{body}");
}

#[test]
fn cli_reference_is_up_to_date() {
    let generated = reference_markdown();
    let path = cli_doc_path();

    if std::env::var_os("UPDATE_DOCS").is_some() {
        std::fs::write(&path, &generated).unwrap_or_else(|err| {
            panic!("writing `{}` failed: {err}", path.display());
        });
        return;
    }

    let expected = std::fs::read_to_string(&path).unwrap_or_else(|err| {
        panic!("reading `{}` failed (run `make update-docs`): {err}", path.display());
    });
    assert_eq!(
        generated, expected,
        "docs/cli.md drifted from the CLI definition; run `make update-docs` if this change is intentional",
    );
}
