//! Keeps `tests/msrv-check/Cargo.toml` in lockstep with the dependency report.
//!
//! The `msrv-check` crate compiles every golden file on the Rust version a
//! consumer needs. To measure a floor that applies to a consumer, it must resolve
//! the same dependency graph a consumer resolves. A consumer builds that graph
//! from the report [`oapi_codegen::deps::required_dependencies`] produces, so that
//! function is the source of truth for this manifest as well.
//!
//! The manifest was written by hand before this test existed. A hand-written copy
//! holds three kinds of drift, and only one of them is loud:
//!
//! 1. A version that differs. Silent: the graph still resolves, and the measured
//!    floor belongs to a dependency set no test exercises.
//! 2. A feature that is absent. Usually loud, because a golden file that uses the
//!    feature fails to compile. Silent when the report recommends a feature that
//!    no golden file exercises.
//! 3. A crate that is absent. Loud, for the same reason.
//!
//! Generating the file closes all three at once. The committed file stays readable
//! and reviewable, and this test fails when it goes stale, which is the pattern
//! `cli_docs.rs` uses for `docs/cli.md`.
//!
//! Set `UPDATE_MSRV_MANIFEST=1` (via `make update-msrv-manifest`) to write the
//! file instead of comparing. See `docs/msrv.md`.

use std::collections::BTreeMap;
use std::path::Path;
use std::path::PathBuf;

use oapi_codegen::deps::Dependency;
use oapi_codegen::deps::required_dependencies;

/// Message at the top of the generated manifest so a reader does not edit it.
const GENERATED_NOTICE: &str = "Generated by `make update-msrv-manifest`. DO NOT EDIT.";

/// The directory holding the committed golden files.
fn generated_dir() -> PathBuf {
    return PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/generated");
}

/// Absolute path to the generated manifest.
fn manifest_path() -> PathBuf {
    return PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/msrv-check/Cargo.toml");
}

/// The union of the crates every golden file references.
///
/// `msrv-check` compiles every golden file as one crate, so it needs one
/// dependency set covering all of them. Two rules make the union safe to compile:
/// a feature any file needs is enabled, and default features stay on unless every
/// file that names the crate can do without them. Both rules err towards a larger
/// graph, because a graph that is too small fails to compile and a graph that is
/// too large only measures a floor that is too high. Neither error is silent.
fn union_of_golden_dependencies() -> Vec<Dependency> {
    let dir = generated_dir();
    let mut entries: Vec<PathBuf> = std::fs::read_dir(&dir)
        .unwrap_or_else(|error| panic!("cannot read `{}`: {error}", dir.display()))
        .map(|entry| {
            return entry
                .unwrap_or_else(|error| panic!("cannot read an entry of `{}`: {error}", dir.display()))
                .path();
        })
        .filter(|path| {
            return path.extension().is_some_and(|extension| return extension == "rs");
        })
        .collect();
    // Sorted so the rendered manifest is byte-identical between a local run and a
    // CI run, which is what lets this test compare rather than merely parse.
    entries.sort();

    assert!(
        !entries.is_empty(),
        "no golden files found in `{}`; the union would be empty and the measured floor meaningless",
        dir.display()
    );

    // Keyed by crate name and ordered by it, so the rendered file is stable.
    let mut union: BTreeMap<&'static str, Dependency> = BTreeMap::new();
    for path in &entries {
        let code =
            std::fs::read_to_string(path).unwrap_or_else(|error| panic!("cannot read `{}`: {error}", path.display()));
        for dep in required_dependencies(&code) {
            let merged = union.entry(dep.name).or_insert_with(|| {
                return Dependency {
                    name: dep.name,
                    version: dep.version,
                    // Start from "not needed" so the fold below can only turn this
                    // on. Starting from `true` would keep default features for a
                    // crate no file needs them for, which enlarges the graph for
                    // every consumer of the measurement.
                    default_features: false,
                    features: Vec::new(),
                };
            });
            assert_eq!(
                merged.version, dep.version,
                "two golden files recommend different versions of `{}`; the report reads one manifest, so this cannot happen",
                dep.name
            );
            merged.default_features = merged.default_features || dep.default_features;
            for feature in dep.features {
                if !merged.features.contains(&feature) {
                    merged.features.push(feature);
                }
            }
        }
    }

    return union
        .into_values()
        .map(|mut dep| {
            // Sorted so a change in golden-file read order cannot rewrite the file.
            dep.features.sort_unstable();
            return dep;
        })
        .collect();
}

/// Render the whole `msrv-check` manifest.
fn render_manifest(deps: &[Dependency]) -> String {
    let mut out = String::new();
    out.push_str(&format!("# {GENERATED_NOTICE}\n"));
    out.push_str(
        "#
# A crate that compiles every committed golden file on the Rust version a
# consumer needs, and does nothing else.
#
# It is not a workspace member, and it must not become one. The workspace builds
# on the pinned toolchain in `rust-toolchain.toml`, which is far newer than the
# floor this crate measures. A member would be compiled by every `cargo` command
# in the repository on that newer toolchain, which is the opposite of the point.
# The `[workspace]` table below detaches it, and the detachment works at this
# depth as well as at the repository root. See `docs/msrv.md`.
[package]
name = \"msrv-check\"
version = \"0.0.0\"
publish = false

# Edition 2021 and not 2024, because edition 2024 needs Rust 1.85. The declared
# floor is above that today, so this is headroom and not a current requirement.
# The emitted code compiles under both editions, so the choice does not change
# what is measured.
edition = \"2021\"

[workspace]

[lib]
path = \"src/lib.rs\"

# The union of every crate the golden files reference, taken from
# `required_dependencies` in `crates/oapi-codegen/src/deps.rs`. That function also
# produces the report a consumer follows, so this crate resolves the graph a
# consumer resolves.
#
# Regenerate with `make update-msrv-manifest`.
[dependencies]
",
    );
    for dep in deps {
        out.push_str(&dep.toml());
        out.push('\n');
    }
    return out;
}

#[test]
fn msrv_check_manifest_is_up_to_date() {
    let generated = render_manifest(&union_of_golden_dependencies());
    let path = manifest_path();

    if std::env::var_os("UPDATE_MSRV_MANIFEST").is_some() {
        std::fs::write(&path, &generated)
            .unwrap_or_else(|error| panic!("writing `{}` failed: {error}", path.display()));
        return;
    }

    let expected = std::fs::read_to_string(&path).unwrap_or_else(|error| {
        panic!(
            "reading `{}` failed (run `make update-msrv-manifest`): {error}",
            path.display()
        )
    });
    assert_eq!(
        generated,
        expected.replace("\r\n", "\n"),
        "`tests/msrv-check/Cargo.toml` drifted from the dependency report; run `make update-msrv-manifest`",
    );
}

/// Every crate the union names must be a dependency of this crate.
///
/// The versions come from this crate's own manifest, so a crate absent from it
/// cannot be given a version at all. `required_dependencies` panics in that case.
/// This test states the requirement directly, so the reason is visible here and
/// not only in a panic message from a generated file.
#[test]
fn every_union_crate_has_a_version() {
    for dep in union_of_golden_dependencies() {
        assert!(
            !dep.version.is_empty(),
            "`{}` has no version requirement in oapi-codegen's manifest",
            dep.name
        );
    }
}

/// The generated manifest must sit next to the crate it configures.
///
/// A path typo would write a manifest nothing reads, and the check above would
/// then compare a file against itself forever.
#[test]
fn the_generated_manifest_configures_the_msrv_check_crate() {
    let root = manifest_path();
    let dir = root
        .parent()
        .unwrap_or_else(|| panic!("the manifest path has a parent directory"));
    assert!(
        Path::new(&dir.join("src/lib.rs")).is_file(),
        "no `src/lib.rs` next to `{}`; the generated manifest configures nothing",
        root.display()
    );
    assert!(
        Path::new(&dir.join("build.rs")).is_file(),
        "no `build.rs` next to `{}`; the golden module list is what that script writes",
        root.display()
    );
}
