//! Keeps the README OpenAPI support matrix in sync with the version manifest.
//!
//! `.github/openapi-versions.json` is the single source of truth for OpenAPI
//! version support; the README table is generated from it. This test rebuilds
//! the table and asserts it matches the committed README. Set `UPDATE_VERSIONS=1`
//! (via `make update-versions`) to rewrite the README instead of comparing.

use std::path::PathBuf;

use serde::Deserialize;

const README: &str = "../../README.md";
const MANIFEST: &str = "../../.github/openapi-versions.json";
const MARKER_BEGIN: &str = "<!-- BEGIN openapi-support (generated by `make update-versions` from .github/openapi-versions.json; DO NOT EDIT) -->";
const MARKER_END: &str = "<!-- END openapi-support -->";
const HEADERS: [&str; 3] = ["Version", "Status", "Notes"];

/// One OpenAPI version entry in the manifest.
#[derive(Deserialize)]
struct Entry {
    version: String,
    status: String,
    #[serde(default)]
    tracking_issue: Option<u64>,
    #[serde(default)]
    supported_since: Option<String>,
}

/// The parsed `.github/openapi-versions.json` manifest.
#[derive(Deserialize)]
struct Manifest {
    repository: String,
    versions: Vec<Entry>,
}

/// Resolve a repository-relative path from the crate root.
fn path(relative: &str) -> PathBuf {
    return PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(relative);
}

/// Capitalize the first character (`planned` -> `Planned`).
fn capitalize(word: &str) -> String {
    let mut chars = word.chars();
    return match chars.next() {
        Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    };
}

/// Render the `Notes` cell, linking to the tracking issue or release.
fn notes(entry: &Entry, repository: &str) -> String {
    return match (entry.status.as_str(), &entry.supported_since, entry.tracking_issue) {
        ("supported", Some(tag), _) => {
            format!("Supported in [`{tag}`](https://github.com/{repository}/releases/tag/{tag}).")
        }
        ("planned", _, Some(issue)) => {
            format!("Tracking [here](https://github.com/{repository}/issues/{issue}).")
        }
        (status, _, _) => format!("{}.", capitalize(status)),
    };
}

/// Render the support matrix as a Prettier-aligned Markdown table.
fn table(manifest: &Manifest) -> String {
    let header = HEADERS.map(str::to_owned);
    let body: Vec<[String; 3]> = manifest
        .versions
        .iter()
        .map(|entry| {
            return [
                format!("v{}", entry.version),
                capitalize(&entry.status),
                notes(entry, &manifest.repository),
            ];
        })
        .collect();

    // Prettier pads every column to its widest cell, with a minimum of three so
    // the separator keeps at least `---`.
    let mut widths = [3_usize; 3];
    for row in std::iter::once(&header).chain(body.iter()) {
        for (width, cell) in widths.iter_mut().zip(row) {
            *width = (*width).max(cell.chars().count());
        }
    }

    let render = |cells: &[String; 3]| -> String {
        let padded: Vec<String> = cells
            .iter()
            .zip(widths)
            .map(|(cell, width)| return format!("{cell:<width$}"))
            .collect();
        return format!("| {} |", padded.join(" | "));
    };
    let separator: Vec<String> = widths.iter().map(|width| return "-".repeat(*width)).collect();

    let mut lines = vec![render(&header), format!("| {} |", separator.join(" | "))];
    lines.extend(body.iter().map(render));
    return lines.join("\n");
}

#[test]
fn readme_matrix_is_up_to_date() {
    let raw = std::fs::read_to_string(path(MANIFEST)).unwrap_or_else(|err| panic!("reading manifest failed: {err}"));
    let manifest: Manifest = serde_json::from_str(&raw).unwrap_or_else(|err| panic!("parsing manifest failed: {err}"));

    let current = std::fs::read_to_string(path(README))
        .unwrap_or_else(|err| panic!("reading README failed: {err}"))
        .replace("\r\n", "\n");
    let begin = current
        .find(MARKER_BEGIN)
        .expect("README is missing the openapi-support begin marker");
    let end = current
        .find(MARKER_END)
        .expect("README is missing the openapi-support end marker");
    let generated = format!(
        "{}{MARKER_BEGIN}\n\n{}\n\n{MARKER_END}{}",
        &current[..begin],
        table(&manifest),
        &current[end + MARKER_END.len()..],
    );

    if std::env::var_os("UPDATE_VERSIONS").is_some() {
        std::fs::write(path(README), &generated).unwrap_or_else(|err| panic!("writing README failed: {err}"));
        return;
    }

    assert_eq!(
        generated, current,
        "README support matrix drifted from .github/openapi-versions.json; run `make update-versions`",
    );
}
