//! Keeps the README OpenAPI support matrix in lockstep with the version
//! manifest.
//!
//! `.github/openapi-versions.json` is the single source of truth for which
//! OpenAPI Specification versions are supported, planned, or unsupported. The
//! support-matrix table in `README.md` is generated from it, so this test
//! regenerates the table and asserts it matches the committed README, failing
//! with the exact command to refresh it. Set `UPDATE_VERSIONS=1` (via
//! `make update-versions`) to write the README instead of comparing.

use std::path::PathBuf;

use serde::Deserialize;

/// Marker opening the generated support-matrix region in `README.md`.
const MARKER_BEGIN: &str =
    "<!-- BEGIN openapi-support (generated by `make update-versions` from .github/openapi-versions.json; DO NOT EDIT) -->";

/// Marker closing the generated support-matrix region in `README.md`.
const MARKER_END: &str = "<!-- END openapi-support -->";

/// Column headers for the rendered support matrix, in display order.
const HEADERS: [&str; 3] = ["Version", "Status", "Notes"];

/// One OpenAPI version entry in the manifest.
#[derive(Debug, Deserialize)]
struct VersionEntry {
    /// Semantic version of the OpenAPI Specification, e.g. `"3.1.0"`.
    version: String,
    /// Support status: `supported`, `planned`, or `unsupported`.
    status: String,
    /// Issue number tracking the work to add support, when applicable.
    #[serde(default)]
    tracking_issue: Option<u64>,
    /// Release tag in which the version became supported, when applicable.
    #[serde(default)]
    supported_since: Option<String>,
}

/// The parsed `.github/openapi-versions.json` manifest.
#[derive(Debug, Deserialize)]
struct Manifest {
    /// `owner/repo` slug used to build issue and release links.
    repository: String,
    /// Known OpenAPI versions, rendered into the README in file order.
    versions: Vec<VersionEntry>,
}

/// Absolute path to the committed `README.md`, resolved from the crate root.
fn readme_path() -> PathBuf {
    return PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../README.md");
}

/// Absolute path to the version manifest, resolved from the crate root.
fn manifest_path() -> PathBuf {
    return PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../.github/openapi-versions.json");
}

/// Capitalize the first character of a status word for display (`planned` ->
/// `Planned`), leaving the remainder untouched.
fn capitalize(word: &str) -> String {
    let mut chars = word.chars();
    return match chars.next() {
        Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    };
}

/// Render the `Notes` cell for a version entry, linking to the tracking issue
/// or the release that introduced support where available.
fn notes_cell(entry: &VersionEntry, repository: &str) -> String {
    return match entry.status.as_str() {
        "supported" => match &entry.supported_since {
            Some(tag) => {
                format!("Supported in [`{tag}`](https://github.com/{repository}/releases/tag/{tag}).")
            }
            None => "Supported.".to_owned(),
        },
        "planned" => match entry.tracking_issue {
            Some(number) => {
                format!("Tracking [here](https://github.com/{repository}/issues/{number}).")
            }
            None => "Planned.".to_owned(),
        },
        "unsupported" => "Not yet supported.".to_owned(),
        other => format!("{}.", capitalize(other)),
    };
}

/// Render the support matrix as a GitHub-flavoured Markdown table whose column
/// widths match Prettier's left-aligned formatting, so the generated README
/// passes `prettier --check`.
fn render_table(manifest: &Manifest) -> String {
    let rows: Vec<[String; 3]> = manifest
        .versions
        .iter()
        .map(|entry| {
            [
                format!("v{}", entry.version),
                capitalize(&entry.status),
                notes_cell(entry, &manifest.repository),
            ]
        })
        .collect();

    // Prettier pads every column to the widest cell (header or body), with a
    // minimum of three so the separator row keeps at least `---`.
    let widths: [usize; 3] = std::array::from_fn(|col| {
        let body = rows.iter().map(|row| row[col].chars().count()).max().unwrap_or(0);
        return HEADERS[col].chars().count().max(body).max(3);
    });

    let format_row = |cells: &[String; 3]| {
        let padded: Vec<String> = cells
            .iter()
            .zip(widths.iter())
            .map(|(cell, width)| format!("{cell:<width$}"))
            .collect();
        return format!("| {} |", padded.join(" | "));
    };

    let header = format_row(&HEADERS.map(str::to_owned));
    let separator = format!("| {} |", widths.iter().map(|width| "-".repeat(*width)).collect::<Vec<_>>().join(" | "));
    let mut lines = vec![header, separator];
    lines.extend(rows.iter().map(format_row));
    return lines.join("\n");
}

/// Splice the freshly rendered table between the README markers, preserving
/// everything outside the generated region.
fn render_readme(current: &str, table: &str) -> String {
    let begin = current
        .find(MARKER_BEGIN)
        .unwrap_or_else(|| panic!("`{}` is missing the `{MARKER_BEGIN}` marker", readme_path().display()));
    let end = current
        .find(MARKER_END)
        .unwrap_or_else(|| panic!("`{}` is missing the `{MARKER_END}` marker", readme_path().display()));

    let before = &current[..begin];
    let after = &current[end + MARKER_END.len()..];
    return format!("{before}{MARKER_BEGIN}\n\n{table}\n\n{MARKER_END}{after}");
}

/// Load and parse the version manifest.
fn load_manifest() -> Manifest {
    let path = manifest_path();
    let raw = std::fs::read_to_string(&path)
        .unwrap_or_else(|err| panic!("reading `{}` failed: {err}", path.display()));
    return serde_json::from_str(&raw)
        .unwrap_or_else(|err| panic!("parsing `{}` failed: {err}", path.display()));
}

#[test]
fn readme_matrix_is_up_to_date() {
    let manifest = load_manifest();
    let table = render_table(&manifest);
    let path = readme_path();
    let current = std::fs::read_to_string(&path)
        .unwrap_or_else(|err| panic!("reading `{}` failed: {err}", path.display()))
        .replace("\r\n", "\n");
    let generated = render_readme(&current, &table);

    if std::env::var_os("UPDATE_VERSIONS").is_some() {
        std::fs::write(&path, &generated)
            .unwrap_or_else(|err| panic!("writing `{}` failed: {err}", path.display()));
        return;
    }

    assert_eq!(
        generated, current,
        "README support matrix drifted from .github/openapi-versions.json; run `make update-versions` if this change is intentional",
    );
}
