//! Emitting the [`crate::ir`] as formatted Rust source.
//!
//! Items are built as a [`proc_macro2::TokenStream`] with `quote!`, parsed into
//! a [`syn::File`] (which guarantees the output is syntactically valid Rust),
//! and pretty-printed with `prettyplease`.

use proc_macro2::TokenStream;
use quote::quote;

use crate::error::Error;
use crate::error::Result;
use crate::ir::Alias;
use crate::ir::Enum;
use crate::ir::EnumKind;
use crate::ir::Field;
use crate::ir::Item;
use crate::ir::Module;
use crate::ir::RustType;
use crate::ir::StringVariant;
use crate::ir::Struct;
use crate::ir::UnionVariant;
use crate::naming::Case;
use crate::naming::to_ident;

/// Header prepended to every generated file.
const HEADER: &str = "// Code generated by oapi-codegen-rust. DO NOT EDIT.\n\n";

/// Render a module of IR items into formatted Rust source.
///
/// Each top-level item is parsed and pretty-printed on its own so that a blank
/// line separates adjacent items — prettyplease otherwise emits them with no
/// separation, which is hard to read when many `pub` items follow each other.
pub fn emit_module(module: &Module) -> Result<String> {
    let mut out = String::from(HEADER);
    for (index, item) in module.items.iter().enumerate() {
        let tokens = emit_item(item)?;
        let file = syn::parse2::<syn::File>(tokens).map_err(|source| {
            return Error::InvalidGeneratedCode { source };
        })?;
        if index > 0 {
            out.push('\n');
        }
        out.push_str(&prettyplease::unparse(&file));
    }
    return Ok(out);
}

/// Render a single top-level item.
fn emit_item(item: &Item) -> Result<TokenStream> {
    let tokens = match item {
        Item::Struct(strukt) => emit_struct(strukt)?,
        Item::Enum(enom) => emit_enum(enom)?,
        Item::Alias(alias) => emit_alias(alias)?,
    };
    return Ok(tokens);
}

/// The derive list applied to every generated type.
fn derives() -> TokenStream {
    return quote! {
        #[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq)]
    };
}

/// Render a doc attribute, or nothing when there is no documentation.
fn doc_attr(doc: &Option<String>) -> TokenStream {
    let tokens = match doc {
        Some(text) => {
            // Leading space matches the `/// text` desugaring rustfmt produces.
            let spaced = format!(" {text}");
            quote! { #[doc = #spaced] }
        }
        None => quote! {},
    };
    return tokens;
}

/// Render a `struct` item.
fn emit_struct(strukt: &Struct) -> Result<TokenStream> {
    let name = strukt.name.to_token();
    let doc = doc_attr(&strukt.doc);
    let derives = derives();

    let mut fields = Vec::with_capacity(strukt.fields.len());
    for field in &strukt.fields {
        fields.push(emit_field(field)?);
    }

    let additional = match &strukt.additional_properties {
        Some(element) => {
            let ty = emit_type(element)?;
            quote! {
                #[serde(flatten)]
                pub additional_properties: std::collections::HashMap<String, #ty>,
            }
        }
        None => quote! {},
    };

    return Ok(quote! {
        #doc
        #derives
        pub struct #name {
            #(#fields)*
            #additional
        }
    });
}

/// Render a single struct field.
fn emit_field(field: &Field) -> Result<TokenStream> {
    let name = field.name.to_token();
    let ty = emit_type(&field.ty)?;
    let doc = doc_attr(&field.doc);

    let mut metas: Vec<TokenStream> = Vec::new();
    if let Some(rename) = &field.rename {
        metas.push(quote! { rename = #rename });
    }
    if !field.required {
        metas.push(quote! { skip_serializing_if = "Option::is_none" });
    }
    let serde_attr = if metas.is_empty() {
        quote! {}
    } else {
        quote! { #[serde(#(#metas),*)] }
    };

    return Ok(quote! {
        #doc
        #serde_attr
        pub #name: #ty,
    });
}

/// Render an `enum` item (string enum or untagged union).
fn emit_enum(enom: &Enum) -> Result<TokenStream> {
    let name = enom.name.to_token();
    let doc = doc_attr(&enom.doc);
    let derives = derives();

    let tokens = match &enom.kind {
        EnumKind::Strings(variants) => {
            let rendered = variants.iter().map(emit_string_variant);
            let rendered: Vec<TokenStream> = rendered.collect();
            quote! {
                #doc
                #derives
                pub enum #name {
                    #(#rendered)*
                }
            }
        }
        EnumKind::Union(variants) => {
            let mut rendered = Vec::with_capacity(variants.len());
            for variant in variants {
                rendered.push(emit_union_variant(variant)?);
            }
            quote! {
                #doc
                #derives
                #[serde(untagged)]
                pub enum #name {
                    #(#rendered)*
                }
            }
        }
    };
    return Ok(tokens);
}

/// Render one unit variant of a string enum.
fn emit_string_variant(variant: &StringVariant) -> TokenStream {
    let name = variant.name.to_token();
    let doc = doc_attr(&variant.doc);
    let serde_attr = match &variant.rename {
        Some(rename) => quote! { #[serde(rename = #rename)] },
        None => quote! {},
    };
    return quote! {
        #doc
        #serde_attr
        #name,
    };
}

/// Render one newtype variant of a union enum.
fn emit_union_variant(variant: &UnionVariant) -> Result<TokenStream> {
    let name = variant.name.to_token();
    let ty = emit_type(&variant.ty)?;
    return Ok(quote! {
        #name(#ty),
    });
}

/// Render a `type X = Y;` alias.
fn emit_alias(alias: &Alias) -> Result<TokenStream> {
    let name = alias.name.to_token();
    let ty = emit_type(&alias.ty)?;
    let doc = doc_attr(&alias.doc);
    return Ok(quote! {
        #doc
        pub type #name = #ty;
    });
}

/// Render a Rust type expression.
fn emit_type(ty: &RustType) -> Result<TokenStream> {
    let tokens = match ty {
        RustType::Bool => quote! { bool },
        RustType::I32 => quote! { i32 },
        RustType::I64 => quote! { i64 },
        RustType::F64 => quote! { f64 },
        RustType::String => quote! { String },
        RustType::Value => quote! { serde_json::Value },
        RustType::Date => quote! { chrono::NaiveDate },
        RustType::DateTime => quote! { chrono::DateTime<chrono::Utc> },
        RustType::Uuid => quote! { uuid::Uuid },
        RustType::Bytes => quote! { Vec<u8> },
        RustType::Vec(inner) => {
            let inner = emit_type(inner)?;
            quote! { Vec<#inner> }
        }
        RustType::Map(inner) => {
            let inner = emit_type(inner)?;
            quote! { std::collections::HashMap<String, #inner> }
        }
        RustType::Option(inner) => {
            let inner = emit_type(inner)?;
            quote! { Option<#inner> }
        }
        RustType::Named(name) => {
            let ident = to_ident(name, Case::Pascal).to_token();
            quote! { #ident }
        }
        RustType::Verbatim(text) => {
            let parsed: TokenStream = text.parse().map_err(|_| {
                return Error::UnsupportedSchema {
                    path: "x-rust-type".to_owned(),
                    reason: format!("value `{text}` is not a valid Rust type expression"),
                };
            })?;
            parsed
        }
    };
    return Ok(tokens);
}
