//! Emitting the [`crate::ir`] as formatted Rust source.
//!
//! Items are built as a [`proc_macro2::TokenStream`] with `quote!`, parsed into
//! a [`syn::File`] (which guarantees the output is syntactically valid Rust),
//! and pretty-printed with `prettyplease`.

use proc_macro2::TokenStream;
use quote::format_ident;
use quote::quote;

use crate::error::Error;
use crate::error::Result;
use crate::ir::Alias;
use crate::ir::Enum;
use crate::ir::EnumKind;
use crate::ir::Field;
use crate::ir::HeaderParam;
use crate::ir::Headers;
use crate::ir::Item;
use crate::ir::Module;
use crate::ir::Operation;
use crate::ir::RustType;
use crate::ir::Service;
use crate::ir::StringVariant;
use crate::ir::Struct;
use crate::ir::UnionVariant;
use crate::naming::Case;
use crate::naming::to_ident;

/// Header prepended to every generated file.
const HEADER: &str = "// Code generated by oapi-codegen-rust. DO NOT EDIT.\n\n";

/// Render a module of IR items into formatted Rust source.
///
/// Each top-level item is parsed and pretty-printed on its own so that a blank
/// line separates adjacent items — prettyplease otherwise emits them with no
/// separation, which is hard to read when many `pub` items follow each other.
pub fn emit_module(module: &Module) -> Result<String> {
    let items = module_items(module)?;
    return render(&items);
}

/// Render a module's models followed by the axum server interface.
pub fn emit_with_service(module: &Module, service: &Service) -> Result<String> {
    let mut items = module_items(module)?;
    items.extend(service_items(service)?);
    return render(&items);
}

/// Lower every IR item in a module into its token stream.
fn module_items(module: &Module) -> Result<Vec<TokenStream>> {
    let mut items = Vec::with_capacity(module.items.len());
    for item in &module.items {
        items.push(emit_item(item)?);
    }
    return Ok(items);
}

/// Pretty-print a sequence of top-level items, one blank line apart.
fn render(items: &[TokenStream]) -> Result<String> {
    let mut out = String::from(HEADER);
    for (index, tokens) in items.iter().enumerate() {
        let file = syn::parse2::<syn::File>(tokens.clone()).map_err(|source| {
            return Error::InvalidGeneratedCode { source };
        })?;
        if index > 0 {
            out.push('\n');
        }
        out.push_str(&prettyplease::unparse(&file));
    }
    return Ok(out);
}

/// Render a single top-level item.
fn emit_item(item: &Item) -> Result<TokenStream> {
    let tokens = match item {
        Item::Struct(strukt) => emit_struct(strukt)?,
        Item::Enum(enom) => emit_enum(enom)?,
        Item::Alias(alias) => emit_alias(alias)?,
    };
    return Ok(tokens);
}

/// The derive list applied to every generated type.
fn derives() -> TokenStream {
    return quote! {
        #[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq)]
    };
}

/// Render a doc attribute, or nothing when there is no documentation.
fn doc_attr(doc: &Option<String>) -> TokenStream {
    let tokens = match doc {
        Some(text) => {
            // Leading space matches the `/// text` desugaring rustfmt produces.
            let spaced = format!(" {text}");
            quote! { #[doc = #spaced] }
        }
        None => quote! {},
    };
    return tokens;
}

/// Render a `struct` item.
fn emit_struct(strukt: &Struct) -> Result<TokenStream> {
    let name = strukt.name.to_token();
    let doc = doc_attr(&strukt.doc);
    let derives = derives();

    let mut fields = Vec::with_capacity(strukt.fields.len());
    for field in &strukt.fields {
        fields.push(emit_field(field)?);
    }

    let additional = match &strukt.additional_properties {
        Some(element) => {
            let ty = emit_type(element)?;
            quote! {
                #[serde(flatten)]
                pub additional_properties: std::collections::HashMap<String, #ty>,
            }
        }
        None => quote! {},
    };

    return Ok(quote! {
        #doc
        #derives
        pub struct #name {
            #(#fields)*
            #additional
        }
    });
}

/// Render a single struct field.
fn emit_field(field: &Field) -> Result<TokenStream> {
    let name = field.name.to_token();
    let ty = emit_type(&field.ty)?;
    let doc = doc_attr(&field.doc);

    let mut metas: Vec<TokenStream> = Vec::new();
    if let Some(rename) = &field.rename {
        metas.push(quote! { rename = #rename });
    }
    if !field.required {
        metas.push(quote! { skip_serializing_if = "Option::is_none" });
    }
    let serde_attr = if metas.is_empty() {
        quote! {}
    } else {
        quote! { #[serde(#(#metas),*)] }
    };

    return Ok(quote! {
        #doc
        #serde_attr
        pub #name: #ty,
    });
}

/// Render an `enum` item (string enum or untagged union).
fn emit_enum(enom: &Enum) -> Result<TokenStream> {
    let name = enom.name.to_token();
    let doc = doc_attr(&enom.doc);
    let derives = derives();

    let tokens = match &enom.kind {
        EnumKind::Strings(variants) => {
            let rendered = variants.iter().map(emit_string_variant);
            let rendered: Vec<TokenStream> = rendered.collect();
            quote! {
                #doc
                #derives
                pub enum #name {
                    #(#rendered)*
                }
            }
        }
        EnumKind::Union(variants) => {
            let mut rendered = Vec::with_capacity(variants.len());
            for variant in variants {
                rendered.push(emit_union_variant(variant)?);
            }
            quote! {
                #doc
                #derives
                #[serde(untagged)]
                pub enum #name {
                    #(#rendered)*
                }
            }
        }
    };
    return Ok(tokens);
}

/// Render one unit variant of a string enum.
fn emit_string_variant(variant: &StringVariant) -> TokenStream {
    let name = variant.name.to_token();
    let doc = doc_attr(&variant.doc);
    let serde_attr = match &variant.rename {
        Some(rename) => quote! { #[serde(rename = #rename)] },
        None => quote! {},
    };
    return quote! {
        #doc
        #serde_attr
        #name,
    };
}

/// Render one newtype variant of a union enum.
fn emit_union_variant(variant: &UnionVariant) -> Result<TokenStream> {
    let name = variant.name.to_token();
    let ty = emit_type(&variant.ty)?;
    return Ok(quote! {
        #name(#ty),
    });
}

/// Render a `type X = Y;` alias.
fn emit_alias(alias: &Alias) -> Result<TokenStream> {
    let name = alias.name.to_token();
    let ty = emit_type(&alias.ty)?;
    let doc = doc_attr(&alias.doc);
    return Ok(quote! {
        #doc
        pub type #name = #ty;
    });
}

/// Render a Rust type expression.
fn emit_type(ty: &RustType) -> Result<TokenStream> {
    let tokens = match ty {
        RustType::Bool => quote! { bool },
        RustType::I32 => quote! { i32 },
        RustType::I64 => quote! { i64 },
        RustType::F64 => quote! { f64 },
        RustType::String => quote! { String },
        RustType::Value => quote! { serde_json::Value },
        RustType::Date => quote! { chrono::NaiveDate },
        RustType::DateTime => quote! { chrono::DateTime<chrono::Utc> },
        RustType::Uuid => quote! { uuid::Uuid },
        RustType::Bytes => quote! { Vec<u8> },
        RustType::Vec(inner) => {
            let inner = emit_type(inner)?;
            quote! { Vec<#inner> }
        }
        RustType::Map(inner) => {
            let inner = emit_type(inner)?;
            quote! { std::collections::HashMap<String, #inner> }
        }
        RustType::Option(inner) => {
            let inner = emit_type(inner)?;
            quote! { Option<#inner> }
        }
        RustType::Named(name) => {
            let ident = to_ident(name, Case::Pascal).to_token();
            quote! { #ident }
        }
        RustType::External { module, name } => {
            let path: syn::Path = syn::parse_str(module).map_err(|_| {
                return Error::UnsupportedSchema {
                    path: "import-mapping".to_owned(),
                    reason: format!("module path `{module}` is not a valid Rust path expression"),
                };
            })?;
            let ident = to_ident(name, Case::Pascal).to_token();
            quote! { #path::#ident }
        }
        RustType::Verbatim(text) => {
            let parsed: TokenStream = text.parse().map_err(|_| {
                return Error::UnsupportedSchema {
                    path: "x-rust-type".to_owned(),
                    reason: format!("value `{text}` is not a valid Rust type expression"),
                };
            })?;
            parsed
        }
    };
    return Ok(tokens);
}

/// Emit the axum server interface: the `Api` trait, per-operation response
/// enums, the `Router` builder, and the internal handler functions.
fn service_items(service: &Service) -> Result<Vec<TokenStream>> {
    let mut items = Vec::new();
    for operation in &service.operations {
        if let Some(query) = &operation.query {
            items.push(emit_struct(query)?);
        }
        if let Some(headers) = &operation.headers {
            items.extend(emit_headers(headers)?);
        }
    }
    items.push(emit_trait(service)?);
    for operation in &service.operations {
        let (enum_def, into_response) = emit_response_enum(operation)?;
        items.push(enum_def);
        items.push(into_response);
    }
    items.push(emit_router(service));
    for operation in &service.operations {
        items.push(emit_handler(operation)?);
    }
    return Ok(items);
}

/// Emit the `Api` trait, one async method per operation.
fn emit_trait(service: &Service) -> Result<TokenStream> {
    let mut methods = Vec::with_capacity(service.operations.len());
    for operation in &service.operations {
        let name = operation.name.to_token();
        let doc = doc_attr(&operation.doc);
        let response = operation.response_enum.to_token();
        let args = emit_method_args(operation)?;
        methods.push(quote! {
            #doc
            fn #name(&self, #(#args),*) -> impl std::future::Future<Output = #response> + Send;
        });
    }
    return Ok(quote! {
        /// Server behaviour: implement one method per operation.
        pub trait Api: Clone + Send + Sync + 'static {
            #(#methods)*
        }
    });
}

/// The typed arguments (path parameters, query struct, header struct, then JSON
/// body) of an operation method.
fn emit_method_args(operation: &Operation) -> Result<Vec<TokenStream>> {
    let mut args = Vec::new();
    for param in &operation.path_params {
        let name = param.name.to_token();
        let ty = emit_type(&param.ty)?;
        args.push(quote! { #name: #ty });
    }
    if let Some(query) = &operation.query {
        let ty = query.name.to_token();
        args.push(quote! { query: #ty });
    }
    if let Some(headers) = &operation.headers {
        let ty = headers.name.to_token();
        args.push(quote! { headers: #ty });
    }
    if let Some(body) = &operation.body {
        let ty = emit_type(body)?;
        args.push(quote! { body: #ty });
    }
    return Ok(args);
}

/// Emit an operation's response enum together with its `IntoResponse` impl.
fn emit_response_enum(operation: &Operation) -> Result<(TokenStream, TokenStream)> {
    let name = operation.response_enum.to_token();
    let mut variants = Vec::with_capacity(operation.responses.len());
    let mut arms = Vec::with_capacity(operation.responses.len());
    for case in &operation.responses {
        let variant = case.variant.to_token();
        let code = proc_macro2::Literal::u16_unsuffixed(case.status);
        let doc = doc_attr(&case.doc);
        let status = quote! {
            const STATUS: axum::http::StatusCode = match axum::http::StatusCode::from_u16(#code) {
                Ok(status) => status,
                Err(_) => panic!("oapi-codegen emitted an invalid HTTP status code"),
            };
        };
        match &case.body {
            Some(body) => {
                let ty = emit_type(body)?;
                variants.push(quote! { #doc #variant(#ty) });
                arms.push(quote! {
                    #name::#variant(body) => {
                        #status
                        (STATUS, axum::Json(body)).into_response()
                    }
                });
            }
            None => {
                variants.push(quote! { #doc #variant });
                arms.push(quote! {
                    #name::#variant => {
                        #status
                        STATUS.into_response()
                    }
                });
            }
        }
    }
    let doc = doc_attr(&operation.doc);
    let enum_def = quote! {
        #doc
        pub enum #name {
            #(#variants),*
        }
    };
    let into_response = quote! {
        impl axum::response::IntoResponse for #name {
            fn into_response(self) -> axum::response::Response {
                match self {
                    #(#arms)*
                }
            }
        }
    };
    return Ok((enum_def, into_response));
}

/// Emit the `Router` builder, grouping operations that share a path so they map
/// onto a single axum route with multiple method handlers.
fn emit_router(service: &Service) -> TokenStream {
    let mut routes = Vec::new();
    let mut index = 0;
    while index < service.operations.len() {
        let path = &service.operations[index].path;
        let mut method_router = TokenStream::new();
        let mut first = true;
        while index < service.operations.len() && service.operations[index].path == *path {
            let operation = &service.operations[index];
            let routing = format_ident!("{}", operation.method);
            let handler = operation.handler.to_token();
            if first {
                method_router = quote! { axum::routing::#routing(#handler::<T>) };
                first = false;
            } else {
                method_router = quote! { #method_router.#routing(#handler::<T>) };
            }
            index += 1;
        }
        routes.push(quote! { .route(#path, #method_router) });
    }
    return quote! {
        /// Build an axum `Router` that dispatches each route to `api`.
        pub fn router<T: Api>(api: T) -> axum::Router {
            axum::Router::new()
                #(#routes)*
                .with_state(api)
        }
    };
}

/// Emit an operation's internal handler: extract the typed inputs, call the
/// `Api` method, and return its response (which is `IntoResponse`).
fn emit_handler(operation: &Operation) -> Result<TokenStream> {
    let handler = operation.handler.to_token();
    let method = operation.name.to_token();
    let response = operation.response_enum.to_token();

    let mut extractors = vec![quote! {
        axum::extract::State(api): axum::extract::State<T>
    }];
    let mut call_args: Vec<TokenStream> = Vec::new();
    if !operation.path_params.is_empty() {
        let names: Vec<proc_macro2::Ident> = operation
            .path_params
            .iter()
            .map(|param| {
                return param.name.to_token();
            })
            .collect();
        let mut types = Vec::with_capacity(operation.path_params.len());
        for param in &operation.path_params {
            types.push(emit_type(&param.ty)?);
        }
        if operation.path_params.len() == 1 {
            let name = &names[0];
            let ty = &types[0];
            extractors.push(quote! { axum::extract::Path(#name): axum::extract::Path<#ty> });
        } else {
            extractors.push(quote! { axum::extract::Path((#(#names),*)): axum::extract::Path<(#(#types),*)> });
        }
        for name in &names {
            call_args.push(quote! { #name });
        }
    }
    if let Some(query) = &operation.query {
        let ty = query.name.to_token();
        extractors.push(quote! { axum_extra::extract::Query(query): axum_extra::extract::Query<#ty> });
        call_args.push(quote! { query });
    }
    if let Some(headers) = &operation.headers {
        let ty = headers.name.to_token();
        extractors.push(quote! { headers: #ty });
        call_args.push(quote! { headers });
    }
    if let Some(body) = &operation.body {
        let ty = emit_type(body)?;
        extractors.push(quote! { axum::Json(body): axum::Json<#ty> });
        call_args.push(quote! { body });
    }

    return Ok(quote! {
        async fn #handler<T: Api>(#(#extractors),*) -> #response {
            api.#method(#(#call_args),*).await
        }
    });
}

/// Emit a header struct and its hand-written `FromRequestParts` implementation.
///
/// Header values are read and parsed individually from the request parts, so
/// the struct cannot derive `serde::Deserialize` the way the query struct does.
/// A missing required header, a non-text value, or a value that fails to parse
/// yields a `400 Bad Request` carrying a short plaintext reason.
fn emit_headers(headers: &Headers) -> Result<Vec<TokenStream>> {
    let name = headers.name.to_token();

    let mut field_defs = Vec::with_capacity(headers.params.len());
    let mut bindings = Vec::with_capacity(headers.params.len());
    let mut idents = Vec::with_capacity(headers.params.len());
    for param in &headers.params {
        let ident = param.name.to_token();
        let doc = doc_attr(&param.doc);
        let mut ty = emit_type(&param.ty)?;
        if !param.required {
            ty = quote! { Option<#ty> };
        }
        field_defs.push(quote! {
            #doc
            pub #ident: #ty,
        });
        bindings.push(emit_header_binding(param)?);
        idents.push(ident);
    }

    let struct_def = quote! {
        #[derive(Debug, Clone)]
        pub struct #name {
            #(#field_defs)*
        }
    };

    let extractor = quote! {
        impl<S> axum::extract::FromRequestParts<S> for #name
        where
            S: Send + Sync,
        {
            type Rejection = (axum::http::StatusCode, String);

            async fn from_request_parts(
                parts: &mut axum::http::request::Parts,
                _state: &S,
            ) -> Result<Self, Self::Rejection> {
                #(#bindings)*
                return Ok(Self { #(#idents),* });
            }
        }
    };

    return Ok(vec![struct_def, extractor]);
}

/// Emit the `let <field> = ...;` binding that reads and parses one header,
/// returning a `400` on a missing required header or an unparseable value.
///
/// String headers are taken verbatim; other scalars are `trim()`-ed before
/// parsing, since HTTP permits optional surrounding whitespace (OWS) that
/// `FromStr` would otherwise reject.
fn emit_header_binding(param: &HeaderParam) -> Result<TokenStream> {
    let ident = param.name.to_token();
    let header_name = &param.header_name;
    let missing_msg = format!("missing required header `{header_name}`");
    let not_text_msg = format!("header `{header_name}` is not valid text");

    let value_expr = if matches!(param.ty, RustType::String) {
        quote! { text.to_owned() }
    } else {
        let ty = emit_type(&param.ty)?;
        let invalid_msg = format!("header `{header_name}` has an invalid value");
        quote! {
            match text.trim().parse::<#ty>() {
                Ok(parsed) => parsed,
                Err(_) => return Err((axum::http::StatusCode::BAD_REQUEST, #invalid_msg.to_owned())),
            }
        }
    };

    let present = if param.required {
        value_expr
    } else {
        quote! { Some(#value_expr) }
    };

    let absent = if param.required {
        quote! { return Err((axum::http::StatusCode::BAD_REQUEST, #missing_msg.to_owned())) }
    } else {
        quote! { None }
    };

    return Ok(quote! {
        let #ident = match parts.headers.get(#header_name) {
            Some(value) => {
                let text = match value.to_str() {
                    Ok(text) => text,
                    Err(_) => return Err((axum::http::StatusCode::BAD_REQUEST, #not_text_msg.to_owned())),
                };
                #present
            }
            None => #absent,
        };
    });
}
