name: Automatic Production PR

on:
  schedule:
    - cron: "0 0 * * 0" # Runs every Sunday at midnight UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  create-prod-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Create temporary GitHub App Token
        id: app
        uses: actions/create-github-app-token@v3
        with:
          owner: ${{ github.repository_owner }}
          client-id: ${{ vars.HOUSEKEEPING_BOT_APP_ID }}
          repositories: ${{ github.event.repository.name }}
          private-key: ${{ secrets.HOUSEKEEPING_BOT_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          ref: develop
          fetch-depth: 0
          token: ${{ steps.app.outputs.token }}

      - name: Create production PR
        uses: alchemaxinc/composite-toolbox/create-production-pr@v1
        with:
          token: ${{ steps.app.outputs.token }}
          pr-title: "chore: to production"
          pr-body: ""
