name: Update Cargo Dependencies
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # Run every Sunday at midnight

jobs:
  update-cargo:
    runs-on: ubuntu-latest
    steps:
      - name: Create temporary GitHub App Token
        id: app
        uses: actions/create-github-app-token@v3
        with:
          owner: ${{ github.repository_owner }}
          client-id: ${{ vars.HOUSEKEEPING_BOT_APP_ID }}
          private-key: ${{ secrets.HOUSEKEEPING_BOT_PRIVATE_KEY }}

      - name: Update Cargo Dependencies
        uses: alchemaxinc/update-deps/cargo@v2
        with:
          token: ${{ steps.app.outputs.token }}
          auto-merge: "true"
          base-branch: "develop"
          merge-method: "squash"
          branch-prefix: "update-cargo"
          pr-title: "fix(deps): update cargo dependencies"
          commit-message: "fix(deps): update cargo dependencies"
